In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    str
 1   Customer_Name          527 non-null    str
 2   Gender                 530 non-null    str
 3   Age                    529 non-null    float64
 4   State                  525 non-null    str
 5   City                   532 non-null    str
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    str
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    str
 11  Payment_Method         520 non-null    str
 12  Internet_Service       529 non-null    str
 13  Tech_Support           524 non-null    str
 14  Senior_Citizen         528 non-null    str
 15  Dependents             533 non-null    str
 16  Churn                  532 non-null    str
 17  Last_Interaction_Date  533 non-null    str
dtypes: float64(4), str(14)
memory usage: 118.4 KB

In [4]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [5]:
df.shape

(535, 18)

In [6]:
df.isna().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      3
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop_duplicates(inplace= True)

In [9]:
df.shape

(535, 18)

In [10]:
df.replace(['N/A', 'Null', '', ' '], np.nan, inplace= True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
531,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
532,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
533,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
534,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [11]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [12]:
df = df.apply(lambda x:x.str.strip() if x.dtype == 'str' else x)

In [13]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     184
Standard    169
Basic       167
basic         2
BASIC         2
Name: count, dtype: int64

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [15]:
df['subscription_type'] = df['subscription_type'].str.title()
df['customer_name'] = df['customer_name'].str.title()
df['city'] = df['city'].str.title()
df['state'] = df['state'].str.title()
df['contract_type'] = df['contract_type'].str.title()
df['churn'] = df['churn'].str.title()
df['gender'] = df['gender'].str.title()

In [16]:
df = df[(df['age']>=18) & (df['age']<=100)]

In [17]:
df = df[df['monthly_charges']>=0]
df = df[df['total_charges']>=0]

In [18]:
df['last_interaction_date'] = pd.to_datetime(df['last_interaction_date'], errors= 'coerce')

In [19]:
df['last_interaction_date'] = df["last_interaction_date"].fillna(df['last_interaction_date'].median())

In [20]:
df['tech_support'] = df['tech_support'].fillna('No')

df['payment_method'] = df['payment_method'].fillna('Unknown')

df['monthly_charges'] = df['monthly_charges'].fillna(df['monthly_charges'].mean())

df['tenure_months'] = df['tenure_months'].fillna(df['tenure_months'].mean())

df['age'] = df['age'].fillna(df['age'].mean())

In [21]:
df['customer_value'] = df["monthly_charges"] * df["tenure_months"]

In [22]:
bins = [0, 12, 24, 48, 72]
label = labels = ["0-12 month", "13-24 month", "25-48 month", "49-72 month"]
df['tenure_group'] = pd.cut(df["tenure_months"],bins=bins, labels=label)

In [23]:
df['senior_flag'] = np.where(df['age']>=60, "senior", "adult")

In [24]:
df['churn_flag'] = df['churn'].map({'Yes':1, 'No':0})

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 533
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            492 non-null    str
 1   customer_name          487 non-null    str
 2   gender                 488 non-null    str
 3   age                    492 non-null    float64
 4   state                  485 non-null    str
 5   city                   487 non-null    str
 6   tenure_months          492 non-null    float64
 7   subscription_type      486 non-null    str
 8   monthly_charges        492 non-null    float64
 9   total_charges          492 non-null    float64
 10  contract_type          490 non-null    str
 11  payment_method         492 non-null    str
 12  internet_service       486 non-null    str
 13  tech_support           492 non-null    str
 14  senior_citizen         486 non-null    str
 15  dependents             491 non-null    str
 16  churn                  490 non-null    str
 17  last_interaction_date  492 non-null    datetime64[us]
 18  customer_value         492 non-null    float64
 19  tenure_group           492 non-null    category
 20  senior_flag            492 non-null    str
 21  churn_flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(6), str(14)
memory usage: 122.5 KB

In [26]:
df.describe()

,age,tenure_months,monthly_charges,total_charges,last_interaction_date,customer_value,churn_flag
count,492.000000,492.000000,492.000000,492.000000,492,492.000000,490.000000
mean,43.191057,36.059548,1359.222033,50363.987561,2025-09-05 13:10:14.634146,50231.467233,0.236735
min,18.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,0.000000
25%,30.000000,19.000000,762.940000,19129.100000,2025-08-24 00:00:00,19125.137500,0.000000
50%,43.000000,37.000000,1308.510000,40668.695000,2025-08-24 00:00:00,40701.195000,0.000000
75%,56.000000,53.000000,1889.437500,74393.410000,2025-08-24 00:00:00,74097.160000,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,1.000000
std,15.401619,20.360662,653.133221,39760.135287,NaN,39647.442978,0.425513

In [27]:
df.isnull().sum()

customer_id              0
customer_name            5
gender                   4
age                      0
state                    7
city                     5
tenure_months            0
subscription_type        6
monthly_charges          0
total_charges            0
contract_type            2
payment_method           0
internet_service         6
tech_support             0
senior_citizen           6
dependents               1
churn                    2
last_interaction_date    0
customer_value           0
tenure_group             0
senior_flag              0
churn_flag               2
dtype: int64

In [28]:
df.to_csv('clean_churn_data.csv', index=False)

In [ ]:
from sqlalchemy import create_engine

username = "postgres"
password = "******"
host = "localhost"
port = "5432"
database = "ChurnDB"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer_churn"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer_churn' in database 'ChurnDB'.